paths:
  data_dir: '../data/split'
  model_save_path: '../ckpt/best_model.pt'

model_params:
  hidden_channels: 512
  out_channels: 256
  num_hgt_layers: 4
  num_hgt_heads: 8
  dropout: 0.1

training_params:
  lr: 0.0001
  weight_decay: 1e-5
  epochs: 600
  warmup_epochs: 10
  early_stopping_patience: 20
  early_stopping_delta: 1e-4
  gpu_id: 0
  grad_clip_norm: 1.0
  monitor_gradients: false

cross_validation:
  k_folds: 10
  cv_seed: 42

loss_and_eval:
  ranking_ks: [1, 3, 5, 10, 20]
  bce_weight: 1.0
  bpr_weight: 0.0
  bpr_neg_per_pos: 5
  bpr_all_pairs: false